project_name: dnstress

before:
  hooks:
    - go mod tidy

builds:
  - id: "main"
    main: ./cmd/main.go
    binary: dnstress
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "arm64"
      - "amd64"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - README.md
      - example.txt

checksum:
  name_template: 'checksums.txt'
